<?php

namespace Database\Seeders;

use App\Models\NodeCategory;
use Illuminate\Database\Seeder;

class NodeCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            // ── Core ──────────────────────────────────────────────────────
            [
                'name' => 'AI & Automation',
                'slug' => 'ai-automation',
                'description' => 'Ask, extract, generate',
                'icon' => '🤖',
                'color' => '#7C3AED',
                'kind' => 'core',
                'sort_order' => 1,
            ],
            [
                'name' => 'Triggers & Events',
                'slug' => 'triggers-events',
                'description' => 'Start your workflow',
                'icon' => '⚡',
                'color' => '#D97706',
                'kind' => 'core',
                'sort_order' => 2,
            ],
            [
                'name' => 'Flow & Logic',
                'slug' => 'flow-logic',
                'description' => 'Conditions, loops, wait',
                'icon' => '🔀',
                'color' => '#0891B2',
                'kind' => 'core',
                'sort_order' => 3,
            ],
            [
                'name' => 'Data & Transform',
                'slug' => 'data-transform',
                'description' => 'Filter, merge, format',
                'icon' => '📊',
                'color' => '#059669',
                'kind' => 'core',
                'sort_order' => 4,
            ],
            [
                'name' => 'Your Custom Nodes',
                'slug' => 'custom',
                'description' => 'Built by your team',
                'icon' => '🔧',
                'color' => '#6B7280',
                'kind' => 'core',
                'sort_order' => 5,
            ],

            // ── Apps ──────────────────────────────────────────────────────
            [
                'name' => 'HTTP Request',
                'slug' => 'http-request',
                'description' => 'Call any web endpoint',
                'icon' => '🌐',
                'color' => '#6B7280',
                'kind' => 'app',
                'sort_order' => 10,
            ],
            [
                'name' => 'Gmail',
                'slug' => 'gmail',
                'description' => 'Send, read and manage Gmail',
                'icon' => '✉️',
                'color' => '#EA4335',
                'kind' => 'app',
                'sort_order' => 20,
            ],
            [
                'name' => 'Google Sheets',
                'slug' => 'google-sheets',
                'description' => 'Read and write spreadsheets',
                'icon' => '🗂️',
                'color' => '#34A853',
                'kind' => 'app',
                'sort_order' => 21,
            ],
            [
                'name' => 'Google Drive',
                'slug' => 'google-drive',
                'description' => 'Files and folders in Drive',
                'icon' => '📁',
                'color' => '#1A73E8',
                'kind' => 'app',
                'sort_order' => 22,
            ],
            [
                'name' => 'Google Calendar',
                'slug' => 'google-calendar',
                'description' => 'Events and reminders',
                'icon' => '📅',
                'color' => '#4285F4',
                'kind' => 'app',
                'sort_order' => 23,
            ],
            [
                'name' => 'Slack',
                'slug' => 'slack',
                'description' => 'Send messages and manage channels',
                'icon' => '💬',
                'color' => '#4A154B',
                'kind' => 'app',
                'sort_order' => 30,
            ],
            [
                'name' => 'Discord',
                'slug' => 'discord',
                'description' => 'Messages and server actions',
                'icon' => '🎮',
                'color' => '#5865F2',
                'kind' => 'app',
                'sort_order' => 31,
            ],
            [
                'name' => 'Telegram',
                'slug' => 'telegram',
                'description' => 'Send and receive messages',
                'icon' => '✈️',
                'color' => '#0088CC',
                'kind' => 'app',
                'sort_order' => 32,
            ],
            [
                'name' => 'Twilio',
                'slug' => 'twilio',
                'description' => 'SMS, voice and verify',
                'icon' => '📞',
                'color' => '#F22F46',
                'kind' => 'app',
                'sort_order' => 33,
            ],
            [
                'name' => 'GitHub',
                'slug' => 'github',
                'description' => 'Repos, issues, pull requests',
                'icon' => '🐙',
                'color' => '#181717',
                'kind' => 'app',
                'sort_order' => 40,
            ],
            [
                'name' => 'GitLab',
                'slug' => 'gitlab',
                'description' => 'Projects, issues, pipelines',
                'icon' => '🦊',
                'color' => '#FC6D26',
                'kind' => 'app',
                'sort_order' => 41,
            ],
            [
                'name' => 'Jira',
                'slug' => 'jira',
                'description' => 'Issues and project tracking',
                'icon' => '🎫',
                'color' => '#0052CC',
                'kind' => 'app',
                'sort_order' => 42,
            ],
            [
                'name' => 'Linear',
                'slug' => 'linear',
                'description' => 'Issues and project cycles',
                'icon' => '📐',
                'color' => '#5E6AD2',
                'kind' => 'app',
                'sort_order' => 43,
            ],
            [
                'name' => 'Trello',
                'slug' => 'trello',
                'description' => 'Cards, boards and lists',
                'icon' => '📋',
                'color' => '#0052CC',
                'kind' => 'app',
                'sort_order' => 44,
            ],
            [
                'name' => 'Notion',
                'slug' => 'notion',
                'description' => 'Pages, databases, blocks',
                'icon' => '📓',
                'color' => '#191919',
                'kind' => 'app',
                'sort_order' => 50,
            ],
            [
                'name' => 'Airtable',
                'slug' => 'airtable',
                'description' => 'Records and base operations',
                'icon' => '🗃️',
                'color' => '#18BFFF',
                'kind' => 'app',
                'sort_order' => 51,
            ],
            [
                'name' => 'HubSpot',
                'slug' => 'hubspot',
                'description' => 'Contacts, deals, pipelines',
                'icon' => '🟠',
                'color' => '#FF7A59',
                'kind' => 'app',
                'sort_order' => 60,
            ],
            [
                'name' => 'Salesforce',
                'slug' => 'salesforce',
                'description' => 'CRM records and queries',
                'icon' => '☁️',
                'color' => '#00A1E0',
                'kind' => 'app',
                'sort_order' => 61,
            ],
            [
                'name' => 'Stripe',
                'slug' => 'stripe',
                'description' => 'Payments and subscriptions',
                'icon' => '💳',
                'color' => '#635BFF',
                'kind' => 'app',
                'sort_order' => 62,
            ],
            [
                'name' => 'Mailchimp',
                'slug' => 'mailchimp',
                'description' => 'Lists, campaigns, audiences',
                'icon' => '🐵',
                'color' => '#FFE01B',
                'kind' => 'app',
                'sort_order' => 63,
            ],
            [
                'name' => 'SendGrid',
                'slug' => 'sendgrid',
                'description' => 'Transactional email delivery',
                'icon' => '📧',
                'color' => '#1A82E2',
                'kind' => 'app',
                'sort_order' => 64,
            ],
            [
                'name' => 'OpenAI',
                'slug' => 'openai',
                'description' => 'GPT, DALL·E, Whisper',
                'icon' => '🤖',
                'color' => '#10A37F',
                'kind' => 'app',
                'sort_order' => 70,
            ],
            [
                'name' => 'AWS S3',
                'slug' => 'aws-s3',
                'description' => 'Objects and buckets in S3',
                'icon' => '🪣',
                'color' => '#FF9900',
                'kind' => 'app',
                'sort_order' => 71,
            ],
            [
                'name' => 'Dropbox',
                'slug' => 'dropbox',
                'description' => 'Files and shared folders',
                'icon' => '📦',
                'color' => '#0061FF',
                'kind' => 'app',
                'sort_order' => 72,
            ],
            [
                'name' => 'MySQL',
                'slug' => 'mysql',
                'description' => 'Query and write MySQL',
                'icon' => '🐬',
                'color' => '#4479A1',
                'kind' => 'app',
                'sort_order' => 80,
            ],
            [
                'name' => 'PostgreSQL',
                'slug' => 'postgresql',
                'description' => 'Query and write Postgres',
                'icon' => '🐘',
                'color' => '#336791',
                'kind' => 'app',
                'sort_order' => 81,
            ],
            [
                'name' => 'MongoDB',
                'slug' => 'mongodb',
                'description' => 'Documents and collections',
                'icon' => '🍃',
                'color' => '#47A248',
                'kind' => 'app',
                'sort_order' => 82,
            ],
            [
                'name' => 'Redis',
                'slug' => 'redis',
                'description' => 'Keys, lists and pub/sub',
                'icon' => '🔴',
                'color' => '#DC382D',
                'kind' => 'app',
                'sort_order' => 83,
            ],
        ];

        foreach ($categories as $category) {
            NodeCategory::query()->updateOrCreate(
                ['slug' => $category['slug']],
                $category,
            );
        }
    }
}
