<?php

namespace Database\Seeders;

use App\Models\WorkflowTemplate;
use Illuminate\Database\Seeder;

class WorkflowTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'name' => 'Webhook to HTTP Request',
                'slug' => 'webhook-to-http-request',
                'description' => 'Receive an incoming webhook and forward the payload to an external HTTP endpoint.',
                'category' => 'automation',
                'icon' => 'bolt',
                'color' => '#F59E0B',
                'tags' => ['webhook', 'http', 'integration'],
                'trigger_type' => 'trigger.webhook',
                'trigger_config' => ['http_method' => 'POST', 'authentication' => 'none'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.webhook', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Webhook']],
                    ['id' => 'action-1', 'type' => 'action.http_request', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'HTTP Request']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Configure the webhook URL and set the target HTTP endpoint in the HTTP Request node.',
                'required_credentials' => [],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Scheduled Data Sync',
                'slug' => 'scheduled-data-sync',
                'description' => 'Run a recurring scheduled job to fetch data from an API and store it.',
                'category' => 'automation',
                'icon' => 'clock',
                'color' => '#6366F1',
                'tags' => ['schedule', 'sync', 'cron'],
                'trigger_type' => 'trigger.schedule',
                'trigger_config' => ['cron' => '0 * * * *', 'timezone' => 'UTC'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.schedule', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Every Hour']],
                    ['id' => 'action-1', 'type' => 'action.http_request', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Fetch Data']],
                    ['id' => 'action-2', 'type' => 'action.transform', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'Transform']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Set your cron expression in the Schedule trigger, then configure the API endpoint and transformation logic.',
                'required_credentials' => [],
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Slack Notification on Webhook',
                'slug' => 'slack-notification-on-webhook',
                'description' => 'Send a Slack message whenever a webhook event is received.',
                'category' => 'communication',
                'icon' => 'chat-bubble-left-right',
                'color' => '#10B981',
                'tags' => ['slack', 'webhook', 'notification'],
                'trigger_type' => 'trigger.webhook',
                'trigger_config' => ['http_method' => 'POST', 'authentication' => 'none'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.webhook', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Webhook']],
                    ['id' => 'action-1', 'type' => 'action.slack', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Send Slack Message']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Connect your Slack credential and set the target channel and message template.',
                'required_credentials' => ['slack'],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Daily Report via Email',
                'slug' => 'daily-report-via-email',
                'description' => 'Generate and email a daily summary report on a fixed schedule.',
                'category' => 'communication',
                'icon' => 'envelope',
                'color' => '#3B82F6',
                'tags' => ['email', 'report', 'schedule', 'daily'],
                'trigger_type' => 'trigger.schedule',
                'trigger_config' => ['cron' => '0 8 * * *', 'timezone' => 'UTC'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.schedule', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Daily 8 AM']],
                    ['id' => 'action-1', 'type' => 'action.http_request', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Fetch Report Data']],
                    ['id' => 'action-2', 'type' => 'action.email', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'Send Email']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Configure the data source URL and set your email recipients and template.',
                'required_credentials' => ['smtp'],
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'CI/CD Deployment Notifier',
                'slug' => 'cicd-deployment-notifier',
                'description' => 'Listen for deployment webhook events and broadcast status updates to your team.',
                'category' => 'devops',
                'icon' => 'server',
                'color' => '#8B5CF6',
                'tags' => ['devops', 'ci-cd', 'deployment', 'webhook'],
                'trigger_type' => 'trigger.webhook',
                'trigger_config' => ['http_method' => 'POST', 'authentication' => 'header'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.webhook', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Deployment Event']],
                    ['id' => 'action-1', 'type' => 'action.condition', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Check Status']],
                    ['id' => 'action-2', 'type' => 'action.slack', 'position' => ['x' => 700, 'y' => 100], 'data' => ['label' => 'Success Notify']],
                    ['id' => 'action-3', 'type' => 'action.slack', 'position' => ['x' => 700, 'y' => 300], 'data' => ['label' => 'Failure Notify']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2', 'data' => ['condition' => 'success']],
                    ['id' => 'e3', 'source' => 'action-1', 'target' => 'action-3', 'data' => ['condition' => 'failure']],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Set the webhook secret for authentication. Connect your Slack credential and configure success/failure channels.',
                'required_credentials' => ['slack'],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 5,
            ],

            // ── 10 new templates ──────────────────────────────────────────────

            [
                'name' => 'GitHub Issue to Slack',
                'slug' => 'github-issue-to-slack',
                'description' => 'Post a Slack message whenever a new GitHub issue is opened.',
                'category' => 'integration',
                'icon' => 'code-bracket',
                'color' => '#1F2937',
                'tags' => ['github', 'slack', 'issue', 'notification'],
                'trigger_type' => 'trigger.webhook',
                'trigger_config' => ['http_method' => 'POST', 'authentication' => 'header'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.webhook', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'GitHub Webhook']],
                    ['id' => 'action-1', 'type' => 'action.condition', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Is "opened"?']],
                    ['id' => 'action-2', 'type' => 'action.slack', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'Post to Slack']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2', 'data' => ['condition' => 'true']],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Add this URL as a GitHub webhook (Issues event). Set the shared secret header and connect your Slack credential.',
                'required_credentials' => ['slack'],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Form Submission to Google Sheets',
                'slug' => 'form-submission-to-google-sheets',
                'description' => 'Capture form submissions via webhook and append each entry as a new row in Google Sheets.',
                'category' => 'data-processing',
                'icon' => 'table-cells',
                'color' => '#16A34A',
                'tags' => ['form', 'google-sheets', 'webhook', 'data'],
                'trigger_type' => 'trigger.webhook',
                'trigger_config' => ['http_method' => 'POST', 'authentication' => 'none'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.webhook', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Form Submission']],
                    ['id' => 'action-1', 'type' => 'action.transform', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Map Fields']],
                    ['id' => 'action-2', 'type' => 'action.google_sheets', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'Append Row']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Point your form to the webhook URL. Connect your Google Sheets credential and select the target spreadsheet and sheet.',
                'required_credentials' => ['google-sheets'],
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Weekly Digest Email',
                'slug' => 'weekly-digest-email',
                'description' => 'Aggregate data from multiple sources every Monday and send a weekly digest email.',
                'category' => 'communication',
                'icon' => 'newspaper',
                'color' => '#0EA5E9',
                'tags' => ['email', 'digest', 'weekly', 'schedule'],
                'trigger_type' => 'trigger.schedule',
                'trigger_config' => ['cron' => '0 9 * * 1', 'timezone' => 'UTC'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.schedule', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Every Monday 9 AM']],
                    ['id' => 'action-1', 'type' => 'action.http_request', 'position' => ['x' => 400, 'y' => 100], 'data' => ['label' => 'Fetch Source A']],
                    ['id' => 'action-2', 'type' => 'action.http_request', 'position' => ['x' => 400, 'y' => 300], 'data' => ['label' => 'Fetch Source B']],
                    ['id' => 'action-3', 'type' => 'action.transform', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'Merge & Format']],
                    ['id' => 'action-4', 'type' => 'action.email', 'position' => ['x' => 1000, 'y' => 200], 'data' => ['label' => 'Send Digest']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'trigger-1', 'target' => 'action-2'],
                    ['id' => 'e3', 'source' => 'action-1', 'target' => 'action-3'],
                    ['id' => 'e4', 'source' => 'action-2', 'target' => 'action-3'],
                    ['id' => 'e5', 'source' => 'action-3', 'target' => 'action-4'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Configure your two data source URLs and set email recipients. Adjust the merge transform to build your digest template.',
                'required_credentials' => ['smtp'],
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Stripe Payment to CRM',
                'slug' => 'stripe-payment-to-crm',
                'description' => 'On a successful Stripe payment, create or update the customer record in your CRM.',
                'category' => 'integration',
                'icon' => 'credit-card',
                'color' => '#635BFF',
                'tags' => ['stripe', 'payment', 'crm', 'integration'],
                'trigger_type' => 'trigger.webhook',
                'trigger_config' => ['http_method' => 'POST', 'authentication' => 'header'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.webhook', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Stripe Webhook']],
                    ['id' => 'action-1', 'type' => 'action.condition', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'payment_intent.succeeded?']],
                    ['id' => 'action-2', 'type' => 'action.transform', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'Map to CRM Fields']],
                    ['id' => 'action-3', 'type' => 'action.http_request', 'position' => ['x' => 1000, 'y' => 200], 'data' => ['label' => 'Upsert CRM Contact']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2', 'data' => ['condition' => 'true']],
                    ['id' => 'e3', 'source' => 'action-2', 'target' => 'action-3'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Register this URL as a Stripe webhook endpoint (payment_intent.succeeded). Add your Stripe webhook secret and CRM API key.',
                'required_credentials' => ['stripe'],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Database Backup Reminder',
                'slug' => 'database-backup-reminder',
                'description' => 'Send a reminder email every night if a database backup job has not been confirmed.',
                'category' => 'devops',
                'icon' => 'circle-stack',
                'color' => '#DC2626',
                'tags' => ['database', 'backup', 'schedule', 'reminder', 'devops'],
                'trigger_type' => 'trigger.schedule',
                'trigger_config' => ['cron' => '0 23 * * *', 'timezone' => 'UTC'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.schedule', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Nightly 11 PM']],
                    ['id' => 'action-1', 'type' => 'action.http_request', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Check Backup Status']],
                    ['id' => 'action-2', 'type' => 'action.condition', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'Backup OK?']],
                    ['id' => 'action-3', 'type' => 'action.email', 'position' => ['x' => 1000, 'y' => 300], 'data' => ['label' => 'Send Alert']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2'],
                    ['id' => 'e3', 'source' => 'action-2', 'target' => 'action-3', 'data' => ['condition' => 'false']],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Set the status API endpoint that confirms backup completion. Configure alert email recipients.',
                'required_credentials' => ['smtp'],
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Lead Enrichment Pipeline',
                'slug' => 'lead-enrichment-pipeline',
                'description' => 'Receive a new lead via webhook, enrich it with external data, and push it to your CRM.',
                'category' => 'data-processing',
                'icon' => 'user-plus',
                'color' => '#F97316',
                'tags' => ['lead', 'enrichment', 'crm', 'data-processing'],
                'trigger_type' => 'trigger.webhook',
                'trigger_config' => ['http_method' => 'POST', 'authentication' => 'none'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.webhook', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'New Lead']],
                    ['id' => 'action-1', 'type' => 'action.http_request', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Enrich with Clearbit']],
                    ['id' => 'action-2', 'type' => 'action.transform', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'Merge Lead + Enrichment']],
                    ['id' => 'action-3', 'type' => 'action.http_request', 'position' => ['x' => 1000, 'y' => 200], 'data' => ['label' => 'Create CRM Contact']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2'],
                    ['id' => 'e3', 'source' => 'action-2', 'target' => 'action-3'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Add your enrichment API key (e.g. Clearbit) and CRM API credentials. Map the merged fields to your CRM schema in the transform node.',
                'required_credentials' => ['clearbit'],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Uptime Monitor Alert',
                'slug' => 'uptime-monitor-alert',
                'description' => 'Ping a list of URLs every 5 minutes and alert via Slack if any return a non-200 status.',
                'category' => 'devops',
                'icon' => 'signal',
                'color' => '#EF4444',
                'tags' => ['uptime', 'monitoring', 'slack', 'alert', 'devops'],
                'trigger_type' => 'trigger.schedule',
                'trigger_config' => ['cron' => '*/5 * * * *', 'timezone' => 'UTC'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.schedule', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Every 5 Minutes']],
                    ['id' => 'action-1', 'type' => 'action.http_request', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Ping URL']],
                    ['id' => 'action-2', 'type' => 'action.condition', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'Status != 200?']],
                    ['id' => 'action-3', 'type' => 'action.slack', 'position' => ['x' => 1000, 'y' => 300], 'data' => ['label' => 'Send Alert']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2'],
                    ['id' => 'e3', 'source' => 'action-2', 'target' => 'action-3', 'data' => ['condition' => 'true']],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Set the target URL in the HTTP Request node. Connect your Slack credential and choose the alert channel.',
                'required_credentials' => ['slack'],
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'CSV to Database Import',
                'slug' => 'csv-to-database-import',
                'description' => 'Trigger a CSV file import via webhook, parse each row, and bulk-insert records into your database.',
                'category' => 'data-processing',
                'icon' => 'arrow-up-tray',
                'color' => '#0D9488',
                'tags' => ['csv', 'import', 'database', 'data-processing'],
                'trigger_type' => 'trigger.webhook',
                'trigger_config' => ['http_method' => 'POST', 'authentication' => 'header'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.webhook', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Upload Event']],
                    ['id' => 'action-1', 'type' => 'action.transform', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Parse CSV']],
                    ['id' => 'action-2', 'type' => 'action.loop', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'For Each Row']],
                    ['id' => 'action-3', 'type' => 'action.http_request', 'position' => ['x' => 1000, 'y' => 200], 'data' => ['label' => 'Insert Record']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2'],
                    ['id' => 'e3', 'source' => 'action-2', 'target' => 'action-3'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'POST the CSV content as a multipart body to the webhook URL. Configure the database API endpoint and field mapping in the transform node.',
                'required_credentials' => [],
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'New User Welcome Email',
                'slug' => 'new-user-welcome-email',
                'description' => 'Send a personalised welcome email sequence when a new user registers.',
                'category' => 'communication',
                'icon' => 'hand-raised',
                'color' => '#7C3AED',
                'tags' => ['email', 'onboarding', 'welcome', 'user'],
                'trigger_type' => 'trigger.webhook',
                'trigger_config' => ['http_method' => 'POST', 'authentication' => 'header'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.webhook', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'User Registered']],
                    ['id' => 'action-1', 'type' => 'action.email', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Welcome Email']],
                    ['id' => 'action-2', 'type' => 'action.delay', 'position' => ['x' => 700, 'y' => 200], 'data' => ['label' => 'Wait 2 Days']],
                    ['id' => 'action-3', 'type' => 'action.email', 'position' => ['x' => 1000, 'y' => 200], 'data' => ['label' => 'Follow-up Email']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2'],
                    ['id' => 'e3', 'source' => 'action-2', 'target' => 'action-3'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Call this webhook from your registration flow. Set SMTP credentials and customise the welcome and follow-up email templates.',
                'required_credentials' => ['smtp'],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Multi-Channel Error Alert',
                'slug' => 'multi-channel-error-alert',
                'description' => 'Receive an error event and simultaneously notify via Slack and email for immediate visibility.',
                'category' => 'devops',
                'icon' => 'exclamation-triangle',
                'color' => '#B91C1C',
                'tags' => ['error', 'alert', 'slack', 'email', 'devops'],
                'trigger_type' => 'trigger.webhook',
                'trigger_config' => ['http_method' => 'POST', 'authentication' => 'header'],
                'nodes' => [
                    ['id' => 'trigger-1', 'type' => 'trigger.webhook', 'position' => ['x' => 100, 'y' => 200], 'data' => ['label' => 'Error Event']],
                    ['id' => 'action-1', 'type' => 'action.transform', 'position' => ['x' => 400, 'y' => 200], 'data' => ['label' => 'Format Message']],
                    ['id' => 'action-2', 'type' => 'action.slack', 'position' => ['x' => 700, 'y' => 100], 'data' => ['label' => 'Slack Alert']],
                    ['id' => 'action-3', 'type' => 'action.email', 'position' => ['x' => 700, 'y' => 300], 'data' => ['label' => 'Email Alert']],
                ],
                'edges' => [
                    ['id' => 'e1', 'source' => 'trigger-1', 'target' => 'action-1'],
                    ['id' => 'e2', 'source' => 'action-1', 'target' => 'action-2'],
                    ['id' => 'e3', 'source' => 'action-1', 'target' => 'action-3'],
                ],
                'viewport' => ['x' => 0, 'y' => 0, 'zoom' => 1],
                'settings' => [],
                'instructions' => 'Send error payloads to this webhook from your application. Connect Slack and SMTP credentials, then set the on-call Slack channel and email recipients.',
                'required_credentials' => ['slack', 'smtp'],
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 15,
            ],
        ];

        foreach ($templates as $template) {
            WorkflowTemplate::updateOrCreate(
                ['slug' => $template['slug']],
                [
                    'name' => $template['name'],
                    'slug' => $template['slug'],
                    'description' => $template['description'],
                    'category' => $template['category'],
                    'icon' => $template['icon'],
                    'color' => $template['color'],
                    'tags' => $template['tags'],
                    'nodes_data' => $template['nodes'],
                    'edges_data' => $template['edges'],
                    'is_featured' => $template['is_featured'],
                    'is_active' => $template['is_active'],
                    'sort_order' => $template['sort_order'],
                ]
            );
        }
    }
}
